server:
  port: 8080
  servlet:
    context-path: /e2e-chat
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e2e-chat
    username: e2echat
    password: '#e2eChat'
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        lob:
          non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  thymeleaf:
    cache: false
